services:
  hugo-blog:
    image: liupengliang/hugo-docker:v6
    # command: "hugo server -w -b http://localhost:1313 --bind=0.0.0.0 --disableFastRender"
    command: "hugo --minify --cleanDestinationDir -t even --environment production"
    restart: always
    container_name: blog
    ports:
      - "1313:1313"
    volumes:
      - ${PWD}/blog:/hugo-site